(library
 (name kite_runtime)
 (modules cluster kubelet feed service volume taint manifest)
 (flags (:standard -warn-error +a)))

(library
 (name kite_execution)
 (modules eval)
 (libraries kite_core)
 (flags (:standard -warn-error +a)))

(library
 (name kite_artifact)
 (modules artifact)
 (libraries kite_execution kite_core kite_surface kite_elab)
 (flags (:standard -warn-error +a)))
